import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import fs from "fs";

let vaultPluginPath = process.env.OBSIDIAN_VAULT_PATH || null;
if (!vaultPluginPath && fs.existsSync("local.config.json")) {
	try {
		const localConfig = JSON.parse(fs.readFileSync("local.config.json", "utf8"));
		vaultPluginPath = localConfig.vaultPluginPath || null;
	} catch (e) {
		console.warn("Emoji Title: Failed to read/parse local.config.json", e);
	}
}

const buildPlugins = [];
if (vaultPluginPath) {
	buildPlugins.push({
		name: 'copy-to-vault',
		setup(build) {
			build.onEnd(() => {
				try { fs.unlinkSync(`${vaultPluginPath}/main.js`); } catch (e) {}
				try { fs.unlinkSync(`${vaultPluginPath}/manifest.json`); } catch (e) {}
				try { fs.unlinkSync(`${vaultPluginPath}/styles.css`); } catch (e) {}
				try { fs.copyFileSync('main.js', `${vaultPluginPath}/main.js`); } catch (e) {}
				try { fs.copyFileSync('manifest.json', `${vaultPluginPath}/manifest.json`); } catch (e) {}
				try { fs.copyFileSync('styles.css', `${vaultPluginPath}/styles.css`); } catch (e) {}
				console.log(`Emoji Title: Copied build to ${vaultPluginPath}`);
			});
		}
	});
} else {
	console.log("Emoji Title: No vault path configured. Skipping copy-to-vault step.");
}

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: 'main.js',
	plugins: buildPlugins
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
