import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const vaultPluginPath = "/Users/arturtupiassu/obsidian/Cofre de Artur Tupiassu/.obsidian/plugins/emoji-title-plugin";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: 'main.js',
	plugins: [{
		name: 'copy-to-vault',
		setup(build) {
			build.onEnd(() => {
				try { fs.unlinkSync(`${vaultPluginPath}/main.js`); } catch (e) {}
				try { fs.unlinkSync(`${vaultPluginPath}/manifest.json`); } catch (e) {}
				fs.copyFileSync('main.js', `${vaultPluginPath}/main.js`);
				fs.copyFileSync('manifest.json', `${vaultPluginPath}/manifest.json`);
			});
		}
	}]
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
